name: assessment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-134.0.dev

dependencies:
  connectivity_plus: ^6.0.5
  flutter:
    sdk: flutter
  http: ^1.2.2
  internet_connection_checker: ^2.0.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

 
